# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 11:18
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_addr', models.GenericIPAddressField(protocol='IPv4')),
                ('dst_addr', models.GenericIPAddressField(protocol='IPv4', validators=[app.models.check_destination_ip])),
                ('dst_port', models.IntegerField()),
                ('tunel_id', models.IntegerField()),
                ('loc_port', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
