# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160622_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarding',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
