# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160309_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortForwarding',
            new_name='Forwarding',
        ),
        migrations.RenameField(
            model_name='forwarding',
            old_name='tunnels',
            new_name='tunnel',
        ),
    ]
