# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160316_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarding',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forwarding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 16, 16, 17, 52, 348643, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
